# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2023b87fc35abacc7d5fa49baddc0ea3fce19d76e2f08c7e982c5f89a13ef136678cab75bd538919f8bfad61e6761043e40c7a214152174ef95800379ef660e8

test:
  secret_key_base: a3ffed600af5766a9d4aa0d80d72fc11df76b4689f1cd1bcb63369359d020604c780422467f582658cf0c374357039b307232c954be500384ab36b2ecda2511d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
